import FitnessOperation as op
op.TypeOfTrainee()
if op=="normal weight":
   print("- for children aged 12 and 13 years should include Meat and legumes: \n meat, chicken, fish, chickpeas, beans, and lentils are important sources of animal and plant proteins, which support the growth and development of the body and muscles and bones in children at this age.Vegetables: vegetables, whether colored or dark, contain many vitamins, minerals, fibers, water, and antioxidants that are important for the child’s growth\n, immunity, activity, and protection from diseases. They are also light on the stomach and easy to digest.\n Dairy products: milk, yogurt, cheese, and other types of dairy products contribute to strengthening and hardening the bones and teeth, due to their richness in minerals such as calcium\n, phosphorus, and potassium. They also contain vitamin A, which enhances the child’s immunity and maintains the health of the eyes and skin.Fruits: getting a variety of fruits throughout the day provides the child with enough vitamins and minerals for his growth and immunity.\n It also makes him feel energetic and active, because it contains natural sugar. Fruits are one of the most important and safest sources of energy for the child at this stage. They compensate him for the manufactured sugars that cause him weight gain and tooth decay.Grains: sources of carbohydrates such as grains, potatoes, rice, pasta are important sources of food for the child because\n they give him high calories and a large amount of fiber that improves his digestive system. They also provide him with the nutrients he needs in his day.\nThe source also provides a table of daily nutritional needs for children aged 12 and 13 years from each food group.\n Healthy fats: they are essential for your brain, heart, skin, and hair health. They also help you absorb fat-soluble vitamins like A, D, E, and K. Choose healthy fats like olive oil, avocado, nuts, seeds, and fatty fish. Avoid saturated fats like butter, cheese, cream, and trans fats like margarine, shortening, and baked goods.\n")
elif op=="over weigh":
    print("Fruits and vegetables: they are low in calories and high in fiber, vitamins, minerals, and antioxidants. They also help you feel full and prevent overeating. Aim for at least five servings of fruits and vegetables per day.\n Whole grains: they are rich in fiber, which helps lower cholesterol and blood sugar levels. They also provide complex carbohydrates that give you energy and keep you satisfied. \n Choose whole wheat bread, brown rice, oatmeal, quinoa, etc. instead of refined grains like white bread, white rice, and pastries.\n Lean protein: they help you build and maintain muscle mass, which boosts your metabolism and burns more calories. They also keep you full and prevent cravings.\n Choose lean sources of protein like fish, poultry, eggs, beans, nuts, and low-fat dairy products. Avoid red meat, processed meat, and fried foods.\n Water: it is vital for your body’s functions and helps you stay hydrated and flush out toxins\n. It also helps you control your appetite and prevent overeating. Drink at least eight glasses of water per day. Avoid sugary drinks like soda, juice, and sports drinks.\n")
elif op=="Slim":
    print("Eat More calories: they are the units of energy that your body needs to function and grow. If you\n are underweight, you need to consume more calories than you burn to gain weight. You can\n use a calorie calculator to estimate how many calories you need per day based on your age,\ngender, height, weight, and activity level\n")
elif op=="first class fat":
    print("contact with me")
elif op=="second class fat":
    print("contact with me")


